version: '3.8'

services:
  db:
    image: postgres:16.8
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: careconnect
      POSTGRES_PASSWORD: QWERTqwert@12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_database.sql

volumes:
  postgres_data:
