- name: Check if kubectl is installed
  command: kubectl version --client=true
  register: kubectl_check
  ignore_errors: yes

- name: Fail if kubectl is not installed
  fail:
    msg: "kubectl not found! Please install kubectl."
  when: kubectl_check.rc != 0

- name: Check if minikube is installed
  command: minikube version
  register: minikube_check
  ignore_errors: yes

- name: Fail if minikube is not installed
  fail:
    msg: "minikube not found! Please install minikube."
  when: minikube_check.rc != 0

- name: Check if minikube is running
  command: minikube status
  register: minikube_status
  ignore_errors: yes

- name: Show minikube status output
  debug:
    var: minikube_status.stdout

- name: Fail if minikube is not running
  fail:
    msg: "Minikube is not running! Please start minikube."
  when: "minikube_status.stdout is not defined or \"host: Running\" not in minikube_status.stdout"