apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      restartPolicy: Always
      containers:
      - name: email-service
        image: shubhpatel2610/email-service:latest
        env:
        - name: SMTP_SERVER
          valueFrom:
            secretKeyRef:
              name: careconnect-db-credentials
              key: smtp-server
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: careconnect-db-credentials
              key: smtp-port
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: careconnect-db-credentials
              key: smtp-username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: careconnect-db-credentials
              key: smtp-password
        - name: RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: careconnect-db-credentials
              key: rabbitmq-host
        - name: RABBITMQ_PORT
          valueFrom:
            secretKeyRef:
              name: careconnect-db-credentials
              key: rabbitmq-port
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: careconnect-db-credentials
              key: rabbitmq-username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: careconnect-db-credentials
              key: rabbitmq-password
        - name: LOGSTASH_HOST
          valueFrom:
            secretKeyRef:
              name: careconnect-db-credentials
              key: logstash-host
        - name: LOGSTASH_PORT
          valueFrom:
            secretKeyRef:
              name: careconnect-db-credentials
              key: logstash-port

