apiVersion: v1
kind: PersistentVolume
metadata:
  name: careconnect-shared-pv
  labels:
    type: local
    app: careconnect
spec:
  storageClassName: "" #standard
  #persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: "/mnt/data/careconnect"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: careconnect-backup-pv
  labels:
    type: local
    app: careconnect
spec:
  storageClassName: "" #standard
  #persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: "/mnt/data/careconnect-backup"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: careconnect-rabbitmq-pv
  labels:
    type: local
    app: careconnect
spec:
  storageClassName: "" #standard
  #persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/rabbitmq"